import { SplitType } from "~/types";

export const ADD_EXPENSE_STEPS = {
  SELECT_FRIENDS_STEP: "SELECT_FRIENDS_STEP",
  SPLIT_AMOUNT_STEP: "SPLIT_AMOUNT_STEP",
  SELECT_SPLIT_STEP: "SELECT_SPLIT_STEP",
  SPLIT_SUCCESS_STEP: "SPLIT_SUCCESS_STEP",
};

export const ADD_EXPENSE_STEPS_SEQUENCE = [
  ADD_EXPENSE_STEPS.SELECT_FRIENDS_STEP,
  ADD_EXPENSE_STEPS.SPLIT_AMOUNT_STEP,
  ADD_EXPENSE_STEPS.SELECT_SPLIT_STEP,
  ADD_EXPENSE_STEPS.SPLIT_SUCCESS_STEP,
];

export const SPLIT_TYPES: {
  EQUAL: SplitType;
  UNEQUAL: SplitType;
  PERCENTAGE: SplitType;
} = {
  EQUAL: "EQUAL",
  UNEQUAL: "UNEQUAL",
  PERCENTAGE: "PERCENTAGE",
};
